export const arrEngKeys = [
  [
    { keyValue: ["`", "~"], side: "l", finger: 5 },
    { keyValue: [1, "!"], side: "l", finger: 5 },
    { keyValue: [2, "@"], side: "l", finger: 4 },
    { keyValue: [3, "#"], side: "l", finger: 3 },
    { keyValue: [4, "$"], side: "l", finger: 2 },
    { keyValue: [5, "%"], side: "l", finger: 2 },
    { keyValue: [6, "^"], side: "r", finger: 2 },
    { keyValue: [7, "&"], side: "r", finger: 2 },
    { keyValue: [8, "*"], side: "r", finger: 3 },
    { keyValue: [9, "("], side: "r", finger: 4 },
    { keyValue: [0, ")"], side: "r", finger: 5 },
    { keyValue: ["-", "_"], side: "r", finger: 5 },
    { keyValue: ["=", "+"], side: "r", finger: 5 },
    { keyValue: "Backspace", side: "r", finger: 5 }
  ],
  [
    { keyValue: "Tab", side: "l", finger: 5 },
    { keyValue: "q", side: "l", finger: 5 },
    { keyValue: "w", side: "l", finger: 4 },
    { keyValue: "e", side: "l", finger: 3 },
    { keyValue: "r", side: "l", finger: 2 },
    { keyValue: "t", side: "l", finger: 2 },
    { keyValue: "y", side: "r", finger: 2 },
    { keyValue: "u", side: "r", finger: 2 },
    { keyValue: "i", side: "r", finger: 3 },
    { keyValue: "o", side: "r", finger: 4 },
    { keyValue: "p", side: "r", finger: 5 },
    { keyValue: ["[", "{"], side: "r", finger: 5 },
    { keyValue: ["]", "}"], side: "r", finger: 5 },
    { keyValue: ["\\", "|"], side: "r", finger: 5 }
  ],
  [
    { keyValue: "Caps Lock", side: "l", finger: 5 },
    { keyValue: "a", side: "l", finger: 5 },
    { keyValue: "s", side: "l", finger: 4 },
    { keyValue: "d", side: "l", finger: 3 },
    { keyValue: "f", side: "l", finger: 2 },
    { keyValue: "g", side: "l", finger: 2 },
    { keyValue: "h", side: "r", finger: 2 },
    { keyValue: "j", side: "r", finger: 2 },
    { keyValue: "k", side: "r", finger: 3 },
    { keyValue: "l", side: "r", finger: 4 },
    { keyValue: [";", ":"], side: "r", finger: 5 },
    { keyValue: ["'", '"'], side: "r", finger: 5 },
    { keyValue: "Enter", side: "r", finger: 5 }
  ],
  [
    { keyValue: "Shift", side: "l", finger: 5 },
    { keyValue: "z", side: "l", finger: 5 },
    { keyValue: "x", side: "l", finger: 4 },
    { keyValue: "c", side: "l", finger: 3 },
    { keyValue: "v", side: "l", finger: 2 },
    { keyValue: "b", side: "l", finger: 2 },
    { keyValue: "n", side: "r", finger: 2 },
    { keyValue: "m", side: "r", finger: 2 },
    { keyValue: [",", "<"], side: "r", finger: 3 },
    { keyValue: [".", ">"], side: "r", finger: 4 },
    { keyValue: ["/", "?"], side: "r", finger: 5 },
    { keyValue: "Shift", side: "r", finger: 5 }
  ],
  [{ keyValue: "Space", side: "lr", finger: 1 }]
];

export const arrRuKeys = [
  [
    { keyValue: "ё", side: "l", finger: 5 },
    { keyValue: [1, "!"], side: "l", finger: 5 },
    { keyValue: [2, '"'], side: "l", finger: 4 },
    { keyValue: [3, "№"], side: "l", finger: 3 },
    { keyValue: [4, ";"], side: "l", finger: 2 },
    { keyValue: [5, "%"], side: "l", finger: 2 },
    { keyValue: [6, ":"], side: "r", finger: 2 },
    { keyValue: [7, "?"], side: "r", finger: 2 },
    { keyValue: [8, "*"], side: "r", finger: 3 },
    { keyValue: [9, "("], side: "r", finger: 4 },
    { keyValue: [0, ")"], side: "r", finger: 5 },
    { keyValue: ["-", "_"], side: "r", finger: 5 },
    { keyValue: ["=", "+"], side: "r", finger: 5 },
    { keyValue: "Backspace", side: "r", finger: 5 }
  ],
  [
    { keyValue: "Tab", side: "l", finger: 5 },
    { keyValue: "й", side: "l", finger: 5 },
    { keyValue: "ц", side: "l", finger: 4 },
    { keyValue: "у", side: "l", finger: 3 },
    { keyValue: "к", side: "l", finger: 2 },
    { keyValue: "е", side: "l", finger: 2 },
    { keyValue: "н", side: "r", finger: 2 },
    { keyValue: "г", side: "r", finger: 2 },
    { keyValue: "ш", side: "r", finger: 3 },
    { keyValue: "щ", side: "r", finger: 4 },
    { keyValue: "з", side: "r", finger: 5 },
    { keyValue: "х", side: "r", finger: 5 },
    { keyValue: "ъ", side: "r", finger: 5 },
    { keyValue: ["\\", "/"], side: "r", finger: 5 }
  ],
  [
    { keyValue: "Caps Lock", side: "l", finger: 5 },
    { keyValue: "ф", side: "l", finger: 5 },
    { keyValue: "ы", side: "l", finger: 4 },
    { keyValue: "в", side: "l", finger: 3 },
    { keyValue: "а", side: "l", finger: 2 },
    { keyValue: "п", side: "l", finger: 2 },
    { keyValue: "р", side: "r", finger: 2 },
    { keyValue: "о", side: "r", finger: 2 },
    { keyValue: "л", side: "r", finger: 3 },
    { keyValue: "д", side: "r", finger: 4 },
    { keyValue: "ж", side: "r", finger: 5 },
    { keyValue: "э", side: "r", finger: 5 },
    { keyValue: "Enter", side: "r", finger: 5 }
  ],
  [
    { keyValue: "Shift", side: "l", finger: 5 },
    { keyValue: "я", side: "l", finger: 5 },
    { keyValue: "ч", side: "l", finger: 4 },
    { keyValue: "с", side: "l", finger: 3 },
    { keyValue: "м", side: "l", finger: 2 },
    { keyValue: "и", side: "l", finger: 2 },
    { keyValue: "т", side: "r", finger: 2 },
    { keyValue: "ь", side: "r", finger: 2 },
    { keyValue: "б", side: "r", finger: 3 },
    { keyValue: "ю", side: "r", finger: 4 },
    { keyValue: [".", ","], side: "r", finger: 5 },
    { keyValue: "Shift", side: "r", finger: 5 }
  ],
  [{ keyValue: "Space", side: "lr", finger: 1 }]
];
